# Site settings
title: International Conference on Atmospheric Environment, Extreme Weather, and Health

url: http://scr2019.caltech.edu/
baseurl: ''

conference_title: "International Conference on Atmospheric Environment, Extreme Weather, and Health"
conference_title_short: "AEH"
year: "2025"
infoline_text: "Thanks for attending AEH 2025, see you again next time!"

# Color settings
color:
  primary-dark: '#204282'
  title: '#ebf0f4'
  links: '#219ab3'
  accent: '#B89E8F'

# conference data
background-image: img/johannes-plenio-J9oL7OBGSns-unsplash.jpg
directions-link: https://www.hkbu.edu.hk/en/quick-links/campus-map.html
map-embed: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d4538.904599093716!2d114.18013525284161!3d22.339378766902694!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3404072f99feb2c7%3A0xba9ddacaeeb21620!2sHong%20Kong%20Baptist%20University!5e0!3m2!1sen!2sus!4v1749096573777!5m2!1sen!2sus
organizer-email : mmgao2@hkbu.edu.hk
registration-page : http://registration.com
upload-form: http://paperupload.com

collections:
  - invited_speakers
  - organizers
  - sessions
  - papers
  - advisors

# Build settings
markdown: kramdown
permalink: pretty
